[program:cross_env_manager]
command=/main/app/cross_env_manager/venv/bin/python3 /main/app/cross_env_manager/app.py
directory=/main/app/cross_env_manager
user=ymsk
autostart=true
autorestart=true
startsecs=10
startretries=3
redirect_stderr=true
stdout_logfile=/main/app/log/cross_env_manager.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
stderr_logfile=/main/app/log/cross_env_manager_error.log
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=0
environment=PYTHONPATH="/main/app/cross_env_manager"
