[program:cross_env_manager]
command=/home/a1/miniconda3/envs/cross_env_manager/bin/gunicorn -w 4 -b 0.0.0.0:5000 app:app
directory=/main/app/mntc/git/toolsForPersonal/projects/agv_system/app/cross_env_manager
user=a1
autostart=true
autorestart=true
startsecs=10
startretries=3
redirect_stderr=true
stdout_logfile=/main/app/log/cross_env_manager.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/main/app/log/cross_env_manager_error.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5
environment=PYTHONPATH="/main/app/mntc/git/toolsForPersonal/projects/agv_system/app/cross_env_manager",PATH="/home/a1/miniconda3/envs/cross_env_manager/bin:%(ENV_PATH)s"